### PR TITLE
Charlie-Updates

### PR DESCRIPTION
**Pull request by Charlie-Kramer**
updates to analytics in notebook

### CODE REVIEW

**Review by Charlie-Kramer — COMMENTED** [review]
added a bunch of stuff to the analytics notebook (also added one more field to get_repo_data.py)

**Review by matthewkrausse — COMMENTED** [review]
Will you remove the dstore file and launch.json file from this pr? You could add those file types to the .gitignore as well.

**Comment by Charlie-Kramer** [comment]
Done, thanks!

**Review by matthewkrausse — APPROVED** [review]
lgtm

**Pull request merged**
